kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: custom-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: custom-role-binding
subjects:
- kind: ServiceAccount
  name: custom-service-account
roleRef:
 kind: Role
 name: custom-role
 apiGroup: rbac.authorization.k8s.io
---   
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-service-account
  annotations:
    authorization.k8s.io/impersonate: "true"
