
name: Prisma Cloud Docker Image Scan
on:
  pull_request:
    branches:
      - 'main'
env:
  SHA: $(git rev-parse HEAD)

jobs:

  generateDirPaths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix with all modules of this repository
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(ls -l | grep '^d' | awk -F ' ' '{print $9}' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-and-scan:
    needs: generateDirPaths
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateDirPaths.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      #- name: Print Directory Structure
      #  run: |
      #     ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      #  shell: bash {0}
      
      - name: Docker Build
        run: |
          echo "--------"
          echo "${{ github.workspace }}/${{ matrix.path }}"
          echo "--------"
          ls ${{ github.workspace }}/${{ matrix.path }}/

        shell: bash {0}   

      # - name: Prisma Cloud image scan
      #   id: scan
      #   uses: PaloAltoNetworks/prisma-cloud-scan@v1
      #   with:
      #     pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
      #     pcc_user: ${{ secrets.PCC_ACCESS_KEY_ID }}
      #     pcc_pass: ${{ secrets.PCC_SECRET_ACCESS_KEY }}
      #     image_name: panwdigitalnative/${{ matrix.inputPath }}:latest

